module.exports = function (grunt) {
 grunt.config.init({
  uglify: {
   build: {
    files: {
     'dist/qf-builder.min.js': 'dist/qf-builder.js',
     'dist/qf-builder-components.min.js': 'dist/qf-builder-components.js'
    }
   }
  },
  watch: {
   compass: {
    files: ['example/*.scss', 'src/*.scss'],
    tasks: ['compass'],
    options: {
     spawn: false
    }
   },
   coffee: {
    files: ['src/*.coffee', 'components/*.coffee', 'example/*.coffee'],
    tasks: ['coffee'],
    options: {
     spawn: false
    }
   }
  },
  karma: {
   min: {
    configFile: 'test/karma-min.config.coffee'
   },
   source: {
    configFile: 'test/karma.config.coffee'
   }
  }
 });

 grunt.config.set("concat", {
  options: {
   separator: ''
  },
  qfbuilder: {
   src: [
    'src/*.js'
   ],
   dest: 'dist/qf-builder.js',
  },
  qfbuilderComponents: {
   src: [
    'components/*.js'
   ],
   dest: 'dist/qf-builder-components.js',
  }
 });

 grunt.registerTask('qf_build', ['concat', 'uglify']);
 grunt.registerTask('test', ['karma']);
 grunt.loadNpmTasks("grunt-contrib-concat");
 grunt.loadNpmTasks('grunt-contrib-watch');
 return grunt.loadNpmTasks('grunt-contrib-uglify');
};

// ---
// generated by coffee-script 1.9.2